name: Build and Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  IPOPT_VERSION: 3.14.6
  CASADI_VERSION: 3.3.5
  EIGEN_VERSION: 3.4.0
  OSQP_VERSION: v0.6.3
  SIMDE_VERSION: v0.7.2
  PROXQP_VERSION: v0.2.13
  QPSWIFT_VERSION: v0.0.2
  BUILD_RELEASE: ON
  ENABLE_SANITIZERS: ON

jobs:
  build_and_run_tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup working directories
        run: |
          mkdir -p build_external
          mkdir -p build

      - name: Install dependencies
        run: |
          sudo apt-get -y install libyaml-cpp-dev libbenchmark-dev python3 python3-pip python3-setuptools python3-wheel ninja-build
          pip3 install meson
          sudo pip3 install --user meson

      - name: Cache Ipopt
        id: cache-ipopt
        uses: actions/cache@v3
        with:
          path: build_external/coinbrew
          key: ${{ runner.os }}-ipopt${{ env.IPOPT_VERSION }}

      - name: Build Ipopt
        if: steps.cache-ipopt.outputs.cache-hit != 'true'
        working-directory: build_external
        run: bash ../ci/shared/install_ipopt.sh

      - name: Install Ipopt
        id: install-ipopt
        working-directory: build_external/coinbrew
        run: sudo ./coinbrew install Ipopt --build-dir build-ipopt --prefix=/usr/local

      - name: Clear Ipopt Cache on failure
        if: failure() && steps.install-ipopt.outcome == 'failure'
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/{owner}/{repo}/actions/caches?key={key}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          key: ${{ runner.os }}-ipopt${{ env.IPOPT_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Casadi
        id: cache-casadi
        uses: actions/cache@v3
        with:
          path: build_external/casadi
          key: ${{ runner.os }}-casadi${{ env.CASADI_VERSION }}

      - name: Build Casadi
        if: steps.cache-casadi.outputs.cache-hit != 'true'
        working-directory: build_external
        run: bash  ../ci/shared/install_casadi.sh

      - name: Install Casadi
        working-directory: build_external/casadi/build
        run: sudo make install

      - name: Install Eigen
        working-directory: build_external
        run: bash  ../ci/shared/install_eigen.sh

      - name: Install osqp
        working-directory: build_external
        run: bash  ../ci/shared/install_osqp.sh

      - name: Install SIMDe
        working-directory: build_external
        run: bash  ../ci/shared/install_simde.sh

      - name: Install ProxQP
        working-directory: build_external
        run: bash  ../ci/shared/install_proxqp.sh

      - name: Install QPSwift
        working-directory: build_external
        run: bash  ../ci/shared/install_qpswift.sh

      - name: Build laopt
        working-directory: build
        run: |
          cmake .. -DBUILD_RELEASE=$BUILD_RELEASE -DENABLE_SANITIZERS=$ENABLE_SANITIZERS
          make -j2

      - name: Test laopt
        working-directory: build
        run: ctest --test-dir tests --verbose
